Issue #92 update last login
micheljung/faf-java-server pull request #109
Opened 2019-01-01 06:08 UTC by Askaholic

Not sure where to set the last login. This works, but I don't think it's ideal. It should probably use the time of the request, but I don't know where that code is.

2019-01-01 07:15 UTC, bukajsytlos commented
Isn't this responsibility of API (https://github.com/FAForever/faf-java-api
)?

On Tue, 1 Jan 2019, 07:34 Coveralls <notifications@github.com wrote:

> [image: Coverage Status] <https://coveralls.io/builds/20856081>
>
> Coverage decreased (-0.01%) to 84.49% when pulling *72f6ff2
> <https://github.com/FAForever/faf-java-server/commit/72f6ff2a6aefa90d7dd719bad788cb94cab2bab4>
> on Askaholic:issue/#92
> <https://github.com/FAForever/faf-java-server/issues/92>-update-last-login*
> into *6263900
> <https://github.com/FAForever/faf-java-server/commit/6263900caa80f561d6d2d1c940013f359250815f>
> on FAForever:develop*.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FAForever/faf-java-server/pull/109#issuecomment-450712556>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIOEpTQn-q1ItWkjJuBkvzO4Z8UFlfwTks5u-wF5gaJpZM4ZlyBF>
> .
>

2019-01-01 14:09 UTC, Brutus5000 commented
@bukajsytlos Currently not. In the current protocol there is still no usage of a oauth JWT for login. Thus you could login to the lobby without logging in to the API.

2019-01-01 14:20 UTC, Brutus5000 requested changes
We should also add a unit test.

2019-01-01 14:20 UTC, Brutus5000 commented on faf-java-server-app/src/main/java/com/faforever/server/security/Login.java
> +  private Date lastLogin;
`java.util.Date` is not used in this project as it was superceeded by the `java.time` package. Please use `java.time.OffsetDateTime` (the `@Temporal` is not required on java.time types)
See `AbstractEntity` as a reference.

2019-01-05 21:05 UTC, Brutus5000 approved these changes

2019-01-05 21:06 UTC, merged