Add more validity states required for some coop leaderboard checks
micheljung/faf-java-server pull request #111
Opened 2019-01-08 18:11 UTC by Askaholic

Related to these proposed db additions:
https://github.com/FAForever/db/pull/187

I've kept SERVER_SHUTDOWN at the bottom since it isn't currently in the DB and doesn't have a permanent id yet.

2019-01-08 18:35 UTC, 1-alex98 approved these changes

2019-01-08 18:37 UTC, 1-alex98 requested changes
pls also set them correctly then

2019-01-12 16:38 UTC, 1-alex98 requested changes

2019-01-12 16:38 UTC, axel1200 commented on faf-java-server-app/src/main/java/com/faforever/server/coop/CoopService.java
> +        log.debug("Game is not valid");
Bad logging statement. If i look at the log this statement will not provide any information to me. Log which game and that it is a ccop game.

2019-01-12 16:38 UTC, axel1200 commented on faf-java-server-app/src/main/java/com/faforever/server/game/Validity.java
> +  OTHER_UNRANK,
What does Other_UNRANK stand for can you add a comment?

2019-01-12 23:22 UTC, Askaholic commented on faf-java-server-app/src/main/java/com/faforever/server/coop/CoopService.java
> +        log.debug("Game is not valid");
That information is already supplied by the previous logging statement. It would be duplicate and useless if I added it here too. Look on line 33

2019-01-12 23:30 UTC, Askaholic commented on faf-java-server-app/src/main/java/com/faforever/server/coop/CoopService.java
> +        log.debug("Game is not valid");
I added the game's validity state to the logging statement.

2019-01-14 18:32 UTC, 1-alex98 submitted a review, later dismissed

2019-02-16 14:00 UTC, micheljung requested changes
Good work!

2019-02-16 14:00 UTC, micheljung commented on faf-java-server-app/src/test/java/com/faforever/server/coop/CoopServiceTest.java
> +@RunWith(MockitoJUnitRunner.Silent.class)
> Using this implementation of the runner is not recommended. Engineers should care for removing unused stubbings because they are dead code, they add unnecessary details, potentially making the test code harder to comprehend.

2019-02-16 14:00 UTC, micheljung commented on faf-java-server-app/src/test/java/com/faforever/server/coop/CoopServiceTest.java
> +    */
`/**` is for JavaDoc, not multi-line comments. Use `//` or `/*` instead

2019-02-16 14:00 UTC, micheljung commented on faf-java-server-app/src/test/java/com/faforever/server/coop/CoopServiceTest.java
> +    when(coopMapRepository.findOneByFilenameLikeIgnoreCase("SCMP_001")).thenReturn(Optional.of(mission));
```suggestion
    verify((coopMapRepository, never()).findOneByFilenameLikeIgnoreCase(any());
```

2019-02-21 06:42 UTC, micheljung commented
Please note Codacy's analysis result

2019-02-21 08:33 UTC, Askaholic commented
Oops. Somehow it was fine with this on the commit where the code actually changed. Strange.

2019-02-24 12:07 UTC, micheljung approved these changes

2019-02-24 12:07 UTC, merged