Feature/#8 allow single connections only
micheljung/faf-java-server pull request #19
Opened 2017-02-22 16:48 UTC by Geosearchef

2017-02-22 16:51 UTC, IDragonfire requested changes

2017-02-22 16:51 UTC, IDragonfire commented on src/main/resources/config/application-dev.yml
> +    url: jdbc:mysql://${DATABASE_ADDRESS:192.168.99.100}/${DATABASE_NAME:faf}?useSSL=false
This should not be part of the PR ;)

2017-02-22 16:52 UTC, IDragonfire approved these changes

2017-02-22 16:52 UTC, Geosearchef commented on src/main/resources/config/application-dev.yml
> +    url: jdbc:mysql://${DATABASE_ADDRESS:192.168.99.100}/${DATABASE_NAME:faf}?useSSL=false
Euhm, you are too fast, I force pushed that exact second you created the review..... ;)

2017-02-22 16:52 UTC, IDragonfire commented
approved means I looked over the code I have not tested it xD

@micheljung What is with unit tests?

2017-02-22 16:56 UTC, micheljung commented
@IDragonfire https://github.com/FAForever/java-guidelines/wiki/Contribution-Guidelines#definition-of-done-dod

2017-02-22 17:03 UTC, micheljung requested changes

2017-02-22 17:03 UTC, micheljung commented on src/main/java/com/faforever/server/integration/legacy/LegacyServicesActivators.java
> +    }
This should be unit tested. Also, you can use `Requests.verify(!playerService.isPlayerOnline(loginRequest.getLogin(), ErrorCode.USER_ALREADY_CONNECTED);`

2017-03-16 12:46 UTC, micheljung requested changes
Almost perfect :)

2017-03-16 12:46 UTC, micheljung commented on src/test/java/com/faforever/server/player/PlayerServiceTest.java
> +  private FafUserDetails mockFafUserDetails() {
Since it's technically not a mock, I recommend to call it `createFafUserDetails()`;

2017-04-05 08:13 UTC, micheljung commented
If you rebase on develop, the build error will be gone and I can merge it

2017-04-06 11:45 UTC, Geosearchef commented
done

2017-04-13 18:15 UTC, micheljung approved these changes

2017-04-13 18:16 UTC, merged